<a href="https://colab.research.google.com/github/Fathimaminhank/learn.-py/blob/main/TASK_8.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

1. Generate a 3 x 3 matrix using random module.

In [12]:
#please provide your answer below this line.
 
import numpy as np
 
array = np.random.randint( 10,size=(3, 3)) 
 
print(array)

[[3 7 2]
 [4 6 5]
 [9 9 4]]


2. Generate two 4 x 4 matrix using numpy and 

 a) Reshape it to 2 x 8matrix and vertically stack it.

 b) Reshape it to 2 x 8 matrix and horizontally stack it.

In [11]:
#please provide your answer below this line.
 
import numpy as np
array1= np.random.randint(10,size=(4,4))
print(array1)
array2=np.random.randint(10,size=(4,4))
print(array2)
x=array1.reshape(2,8)
y=array2.reshape(2,8)
print (np.vstack((x,y)))
print (np.hstack((x,y)))

[[1 8 8 3]
 [4 6 9 0]
 [9 2 5 5]
 [7 1 3 2]]
[[8 9 6 7]
 [3 1 7 8]
 [3 3 5 1]
 [8 9 9 0]]
[[1 8 8 3 4 6 9 0]
 [9 2 5 5 7 1 3 2]
 [8 9 6 7 3 1 7 8]
 [3 3 5 1 8 9 9 0]]
[[1 8 8 3 4 6 9 0 8 9 6 7 3 1 7 8]
 [9 2 5 5 7 1 3 2 3 3 5 1 8 9 9 0]]
