<a href="https://colab.research.google.com/github/Fathimaminhank/learn.-py/blob/main/TASK_10.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

1. Generate two  3 x 3 matrix and find it's dot product and take the transpose of the answer.

In [8]:
#please provide your answer below this
import numpy as np
a= np.arange(0,9).reshape(3,3)
b= np.arange(2,11).reshape(3,3)
print(a)
print(b)
c=np.dot(a,b)
print(c)
print(np.transpose(c))

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]
[[ 21  24  27]
 [ 66  78  90]
 [111 132 153]]
[[ 21  66 111]
 [ 24  78 132]
 [ 27  90 153]]


2. Create a 3x3 matrix with elements [55,25,15], [30,44,2], [11,45,77] . Now find the determinant of the given matrix.

In [2]:
#please provide your answer below this line.
 
import numpy as np
a=np.array([[55,25,15],[30,44,2],[11,45,77]])
print(a)
det=np.linalg.det(a)
print(int(det))

[[55 25 15]
 [30 44  2]
 [11 45 77]]
137180
